### PR TITLE
Optimized plugin

### PR DESCRIPTION
**Pull request by Timongcraft**
- Optimizes the code in general
- Automatically sets enforce-secure-profile in server.properties
- Uses translations for whisper commands
- Removed teammsg command from whisper commands because they need to be handled differently

### CODE REVIEW

**Comment by Blayung** [comment]
Oh, hello again.

**Comment by Blayung** [comment]
I've looked at the code, and the only doubt I have is that we are using some bungee api. How do these translations work, and why do they require these? I'm really less experienced than you in minecraft plugin making, but isn't bungee some minecraft server engine for connecting multiple servers together? Won't that make the plugin dependant on it?

**Comment by Timongcraft** [comment]
Hello Blayung,
yes you're right about bungeecord's usage. The creator of bungee, md_5, also contributes to spigot. As a result, he added the bungee components to spigot. And using it is the best way to have translatables without an external library.

**Comment by Timongcraft** [comment]
And no, it doesn't make the plugin dependent because it is build in.

**Comment by Blayung** [comment]
Okay, I've merged it. Thank you!

**Comment by Blayung** [comment]
I'll make a release tomorrow or on saturday, if you wanna use it rn, then just use your own compiled version.

**Comment by Blayung** [comment]
Just released a version with your changes! :D

**Pull request merged**
